modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/ellie-mcquinn/storage-options/issues"

[[mods]]
modId = "ellsso"
version = "${version}"
displayName = "Ellie's Storage Options"
#updateJSONURL="https://api.modrinth.com/updates/ellies-storage-options/forge_updates.json"
displayURL = "https://modrinth.com/project/ellies-storage-options"
logoFile = "ellsso.png"
logoBlur = false

authors = "Ellie McQuinn"
description = "Adds some useful and pretty storage options ^_^"

[[dependencies.ellsso]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ellsso]]
modId = "minecraft"
type = "required"
versionRange = "${nf_minecraft_constraint}"
ordering = "NONE"
side = "BOTH"

[[dependencies.ellsso]]
modId = "kotlinforforge"
type = "required"
versionRange = "[${neoforge_kotlin_version},)"
ordering = "NONE"
side = "BOTH"